Fix install interface

diff --git a/scripts/termux-box b/scripts/termux-box
--- a/scripts/termux-box
+++ b/scripts/termux-box
@@ -4,34 +4,47 @@ cd $HOME/termux-box
 
 . $HOME/termux-box/ubuntu-fs/opt/termux-style/termux-style
 
+. $HOME/termux-box/ubuntu-fs/opt/dialogs
+
 apply-termux-style
 
 if [ ! -e ubuntu-fs/opt/wine ]; then
-    echo "Select which Wine to download"
-    echo "1) 8.19 staging"
-    echo "2) 8.22 ge-custom"
-    echo "3) 8.0 proton experimental"
-    read opcode
-    case $opcode in
+    dialog_menu "Termux-Box" "Select which Wine to download: " \
+    "1" "8.19 staging" \
+    "2" "8.22 ge-custom" \
+    "3" "8.0 proton experimental"
+    case $? in
     1)
-    if ! wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/8.19/wine-8.19-staging-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
-    echo "Download failed, restart termux-box"
-    exit
-    fi
-    ;;
+        dialog_loading "Downloading Wine 8.19 staging" &
+        loading_process=$!
+        wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/8.19/wine-8.19-staging-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz &>/dev/null
+        if [ ! -f ubuntu-fs/opt/wine.tar.xz ]; then
+            echo "Download failed, restart termux-box"
+            exit
+        fi
+        kill $loading_process
+        ;;
     2)
-    if ! wget -q --show-progress https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-22/wine-lutris-GE-Proton8-22-x86_64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
-    echo "Download failed, restart termux-box"
-    exit
-    fi
-    ;;
+        dialog_loading "Downloading Wine 8.22 ge-custom" &
+        loading_process=$!
+        wget -q --show-progress https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-22/wine-lutris-GE-Proton8-22-x86_64.tar.xz -O ubuntu-fs/opt/wine.tar.xz &>/dev/null
+        if [ ! -f ubuntu-fs/opt/wine.tar.xz ]; then
+            echo "Download failed, restart termux-box"
+            exit
+        fi
+        kill $loading_process
+        ;;
     3)
-    if ! wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/proton-exp-8.0/wine-proton-exp-8.0-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
-    echo "Download failed, restart termux-box"
-    exit
-    fi
-    touch ubuntu-fs/opt/patch-re8
-    ;;
+        dialog_loading "Downloading Wine 8.0 proton experimental" &
+        loading_process=$!
+        wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/proton-exp-8.0/wine-proton-exp-8.0-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz &>/dev/null
+        if [ ! -f ubuntu-fs/opt/wine.tar.xz ]; then
+            echo "Download failed, restart termux-box"
+            exit
+        fi
+        kill $loading_process
+        touch ubuntu-fs/opt/patch-re8
+        ;;
     esac
 fi
 
@@ -58,11 +71,10 @@ cp -n ubuntu-fs/opt/dxvk.conf /sdcard/termux-box >/dev/null 2>&1
 cp -n ubuntu-fs/opt/vkd3d.conf /sdcard/termux-box >/dev/null 2>&1
 negus=$(cat ubuntu-fs/opt/script.conf)
 if [ "$negus" = "" ]; then
-    echo ""
-    echo "Select containerization method"
-    echo "1) Proot"
-    echo "2) Chroot (root only)"
-    read oleg
+    dialog_menu "Termux-Box" "Select containerization method" \
+    "1" "Proot" \
+    "2" "Chroot (root only)"
+    export oleg=$?
 elif [ "$negus" = "proot" ]; then
     oleg=1
 else
